import { chromium } from 'playwright';
const b = await chromium.connectOverCDP('http://localhost:9222');
const page = await b.contexts()[0].newPage();
await page.setViewportSize({width:1440,height:1000});
await page.goto('https://kmong.com/my-gigs',{waitUntil:'domcontentloaded',timeout:40000});
await page.waitForTimeout(4500);
await page.screenshot({path:'/tmp/km-mygigs.png', clip:{x:0,y:0,width:1440,height:1000}});
const t = await page.evaluate(()=>document.body.innerText.slice(0,1200));
console.log(t.replace(/\n{2,}/g,'\n'));
const links = await page.evaluate(()=>[...new Set([...document.querySelectorAll('a')].map(a=>a.getAttribute('href')).filter(h=>h&&/gig|edit|781350/.test(h)))]);
console.log('\n링크:', links.slice(0,20).join('\n      '));
await page.close(); await b.close();
